args <- commandArgs(trailingOnly=TRUE)
data_path <- ifelse(length(args)>=1, args[1], '../data/patients.csv')
out_png <- ifelse(length(args)>=2, args[2], '../images/patient_diseases_r.png')
library(ggplot2)
if (!file.exists(data_path)) stop('Data not found')
dat <- read.csv(data_path, stringsAsFactors=FALSE)
p <- ggplot(dat, aes(x=disease)) + geom_bar() + ggtitle('Patients by Disease') + theme_minimal()
ggsave(out_png, plot=p, width=7, height=4)
cat('Saved', out_png, '\n')
